# Generated by Django 2.2.7 on 2019-12-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=32)),
                ('email_address', models.EmailField(max_length=254)),
                ('times', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bcId', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=32)),
                ('product_version', models.CharField(max_length=32)),
                ('product_category', models.CharField(max_length=32)),
                ('product_hashLink', models.CharField(max_length=64)),
                ('product_descLink', models.CharField(max_length=64)),
                ('product_status', models.BooleanField()),
                ('product_state', models.CharField(max_length=512)),
                ('product_price', models.CharField(max_length=128)),
                ('product_show_time', models.DateField()),
                ('product_blocknum', models.BigIntegerField()),
                ('product_timestamp', models.BigIntegerField()),
                ('product_transactionHash', models.CharField(max_length=128)),
                ('product_suffix', models.CharField(max_length=64)),
                ('product_index', models.IntegerField()),
                ('product_address', models.CharField(max_length=128)),
                ('product_encrypt', models.CharField(max_length=64)),
                ('product_verify', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=True, to='Owner.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_adress', models.ImageField(upload_to='image')),
                ('img_label', models.CharField(max_length=32)),
                ('img_description', models.TextField()),
                ('product', models.ForeignKey(on_delete=True, to='Owner.Product')),
            ],
        ),
    ]
