# Generated by Django 2.2.7 on 2019-12-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bcId', models.CharField(max_length=32)),
                ('product_permit1', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Password2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_bcId', models.CharField(max_length=32)),
                ('product_permit2', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
