# Generated by Django 2.2.7 on 2019-12-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_password1_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password1',
            old_name='product_permit1',
            new_name='product_permit',
        ),
        migrations.RenameField(
            model_name='password2',
            old_name='product_permit2',
            new_name='product_permit',
        ),
    ]
