# Generated by Django 2.2.7 on 2019-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_auto_20191208_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='password1',
            name='product_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='password2',
            name='product_address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
