# Generated by Django 2.2.7 on 2019-12-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0004_auto_20191208_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password1',
            name='product_address',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='password2',
            name='product_address',
            field=models.CharField(max_length=128),
        ),
    ]
