# Generated by Django 2.2.7 on 2019-12-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0005_auto_20191208_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_encrypt',
            new_name='product_key',
        ),
        migrations.AddField(
            model_name='product',
            name='product_offset',
            field=models.CharField(default='', max_length=64),
        ),
    ]
