# Generated by Django 2.2.7 on 2019-12-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_auto_20191208_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offset',
            field=models.CharField(max_length=64),
        ),
    ]
