# Generated by Django 2.2.7 on 2019-12-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0009_auto_20191218_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_authorization',
        ),
    ]
