# Generated by Django 2.2.7 on 2019-12-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('nickname', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=128)),
                ('type', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=True, to='Buyer.Buyer')),
                ('owner', models.ForeignKey(on_delete=True, to='Owner.Owner')),
                ('product', models.ForeignKey(on_delete=True, to='Owner.Product')),
            ],
        ),
    ]
