# Generated by Django 2.2.7 on 2019-12-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='msg',
            field=models.CharField(max_length=512),
        ),
    ]
