# Generated by Django 2.2.7 on 2019-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20191205_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='time',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
