# Generated by Django 2.2.7 on 2019-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_msg_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='time',
            field=models.CharField(max_length=128),
        ),
    ]
