# Generated by Django 2.2.7 on 2019-12-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0007_auto_20191208_1625'),
        ('Buyer', '0004_auto_20191205_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=32)),
                ('blocknum', models.BigIntegerField()),
                ('purchaseId', models.BigIntegerField()),
                ('timestamp', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('buyer', models.ForeignKey(on_delete=True, to='Buyer.Buyer')),
                ('product', models.ForeignKey(on_delete=True, to='Owner.Product')),
            ],
        ),
    ]
