# Generated by Django 2.2.7 on 2019-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0005_purchasemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemessage',
            name='product_transactionHash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
