# Generated by Django 2.2.7 on 2019-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0006_purchasemessage_product_transactionhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemessage',
            name='product_transactionHash',
            field=models.CharField(max_length=128),
        ),
    ]
