# Generated by Django 2.2.7 on 2019-12-10 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_auto_20191210_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasemessage',
            old_name='product_transactionHash',
            new_name='transactionHash',
        ),
    ]
