# Generated by Django 2.2.7 on 2019-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_auto_20191210_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemessage',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
